# Generated by Django 4.2.10 on 2024-03-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='username',
        ),
    ]
